cloudbuild.yml
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
=> Bootstrap cloudbuild

src/modules/scraper/adapter/messaging/FillEventsConsumer.ts, src/modules/scraper/model/deposit.entity.ts
Signed-off-by: amateima <amatei@umaproject.org>
https://linear.app/uma/issue/ACX-19/use-the-totalfilledamount-param-to-uniquely-identify-fill-events
=> fix: improve processing of fill events

src/modules/configuration/index.ts, src/modules/referral/module.ts, src/modules/referral/services/queries.ts, src/modules/referral/services/service.ts
Signed-off-by: amateima <amatei@umaproject.org>
When computing ACX rewards, the token price should be 0.1$
https://linear.app/uma/issue/ACX-42/change-acx-token-price-to-01dollar
=> fix: make ACX price 0.1$

migrations/1656523050783-Deposit.ts
https://linear.app/uma/issue/ACX-44/change-the-way-referrals-are-counted-for-rewards
Signed-off-by: amateima <amatei@umaproject.org>
=> fix: update referrals counter

src/modules/referral/services/queries.ts, src/modules/referral/services/service.ts
Signed-off-by: amateima <amatei@umaproject.org>
https://linear.app/uma/issue/ACX-72/update-tier-computation-logic
=> fix: update tier calculation

src/modules/referral/services/queries.ts
This PR updates the queries with the correct referral rate calculations
=> fix: fix referral rate calculation

migrations/1658221793203-Deposit.ts, src/modules/referral/services/queries.ts, src/modules/scraper/adapter/messaging/FillEventsConsumer.ts, src/modules/scraper/model/deposit.entity.ts
https://linear.app/uma/issue/ACX-75/make-rewards-capped-at-012percent
=> feat: make realized lp fee capped at 0.12%

src/modules/referral/services/queries.ts, src/modules/referral/services/service.ts
This PR adds the total count for the referrals table data. It is needed to compute the total number of pages
=> fix: add total for referrals table

migrations/1658221793206-MaterializedView.ts
https://linear.app/uma/issue/ACX-100/change-rewards-multiplier-to-2
=> improve: change rewards bonus

cloudbuild-stage.yml
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
=> Cloudbuild: Add stage build

README.md, migrations/1658221793207-MaterializedView.ts, src/modules/referral/services/queries.ts
https://linear.app/uma/issue/ACX-109/get-all-referral-data-from-the-materialized-view
=> improve: use materialized view instead of base tables

cloudbuild-stage.yml
Signed-off-by: Evaldo Felipe <contato@evaldofelipe.com>
=> Update stage docker tag

migrations/1658221793207-MaterializedView.ts, migrations/1659106715325-Deposit.ts, migrations/1659106715326-MaterializedView.ts, src/modules/referral/services/queries.ts, src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts, src/modules/scraper/adapter/messaging/FillEventsConsumer.ts, src/modules/scraper/adapter/messaging/index.ts, src/modules/scraper/model/deposit.entity.ts
https://linear.app/uma/issue/ACX-88/depositrelayerfeepct-should-use-blended-relayerfeepct-of-all-fills
This can't be merged until Evaldo fixes a Zion issue. Currently, the `stage` commits are deployed on both staging and production environments.
=> feat: add relayerFee as part of the bridge fee (DO NOT MERGE)

src/modules/referral/services/cron-service.ts, src/modules/scraper/service.ts
The zion deployment issue has been fixed. Now we can make the deployments safely
=> fix: re-enable env vars

src/modules/referral/services/queries.ts
https://linear.app/uma/issue/ACX-116/referrals-tx-incorrect-sorting
Fix sorting issue on the referrals table
=> feat: fix sorting bug

src/modules/scraper/adapter/messaging/FillEventsConsumer.ts, test/scraper.e2e-spec.ts
https://linear.app/uma/issue/ACX-21/the-same-fill-event-should-not-be-processed-twice
=> feat: assert fill events can't be processed twice

package.json, src/app.module.ts, src/modules/deposit/controller.ts, src/modules/deposit/dto.ts, src/modules/deposit/module.ts, src/modules/deposit/service.ts, src/modules/scraper/adapter/db/deposit-fixture.ts, test/deposit.e2e-spec.ts
This adds a deposit module that contains an endpoint to retrieve deposits from the db.
TODOs:
=> feat: GET /deposits endpoint

src/modules/market-price/adapters/coingecko/index.ts
This PR adds the Coin Gecko id of the balancer token
=> feat: add balancer coingecko id

.env.sample, src/modules/configuration/index.ts, src/modules/scraper/service.ts
This PR adds a higher default block head following distance and allows us to configure these values via env vars.
=> feat: configurable following distances

src/modules/airdrop/entry-points/http/controller.ts, src/modules/airdrop/entry-points/http/dto.ts, src/modules/airdrop/module.ts, src/modules/airdrop/services/airdrop-service.ts, src/modules/configuration/index.ts
Allow to edit the wallet rewards for a particular address. This will be enabled only on the staging environment
=> feat: allow editing wallet rewards

src/modules/auth/auth.module.ts
Increase the expiration deadline from 7 days to 31 days
=> feat: increase JWT expiration (stage)

src/modules/auth/auth.module.ts
This is the prod release of the #94
=> feat: increase JWT expiration (prod)

migrations/1666867200884-Deposit.ts, src/modules/messaging/service.ts, src/modules/scraper/adapter/messaging/DepositFilledDateConsumer.ts, src/modules/scraper/adapter/messaging/FillEventsConsumer.ts, src/modules/scraper/adapter/messaging/index.ts, src/modules/scraper/entry-point/http/controller.ts, src/modules/scraper/entry-point/http/dto.ts, src/modules/scraper/model/deposit.entity.ts, src/modules/scraper/module.ts, src/modules/scraper/service/ScraperQueuesService.ts
=> feat: add filled date to deposits (prod)

migrations/1666019035195-MerkleDistributorWindow.ts, migrations/1666019035196-MerkleDistributorRecipient.ts, src/modules/airdrop/adapter/db/merkle-distributor-recipient.ts, src/modules/airdrop/adapter/db/merkle-distributor-window-fixture.ts, src/modules/airdrop/entry-points/http/controller.ts, src/modules/airdrop/entry-points/http/dto.ts, src/modules/airdrop/model/merkle-distributor-recipient.entity.ts, src/modules/airdrop/model/merkle-distributor-window.entity.ts, src/modules/airdrop/module.ts, src/modules/airdrop/services/airdrop-service.ts, src/modules/airdrop/services/exceptions.ts, src/modules/database/database.providers.ts, test/airdrop/merkle-distributor-duplicate-window.json, test/airdrop/merkle-distributor.e2e-spec.ts, test/airdrop/merkle-distributor.json, test/jest-e2e.json
=> feat: inject and serve merkle distributor claims (prod)

migrations/1667822226389-Deposit.ts, migrations/1667824679940-DepositsMv.ts, src/modules/configuration/index.ts, src/modules/database/database.providers.ts, src/modules/deposit/model/DepositsMv.entity.ts, src/modules/referral/entry-points/http/controller.ts, src/modules/referral/entry-points/http/dto.ts, src/modules/referral/module.ts, src/modules/referral/services/service.ts, src/modules/scraper/model/deposit.entity.ts, test/referrals.e2e-spec.ts
This adds endpoints to prepare or reset deposits for a referral rewards merkle distribution.
=> feat: POST/DELETE /referrals/merkle-distribution

src/modules/airdrop/entry-points/http/controller.ts, src/modules/airdrop/services/airdrop-service.ts
=> feat: add endpoint for eligible rewards wallets (prod)

migrations/1668339782209-Deposit.ts, src/modules/deposit/adapter/db/queries.ts, src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts, src/modules/scraper/model/deposit.entity.ts
Production deployment for #132
=> fix: improve avg fill time (prod)

src/modules/airdrop/services/airdrop-service.ts, test/airdrop.e2e-spec.ts
This reverts commit 4057eb2566e51e5ade6d1506e0cfd880fbfcbca8.
=> hotfix: revert "fix: Fix decimals in welcome traveler completion script" (prod)

src/modules/deposit/dto.ts, src/modules/deposit/service.ts
https://linear.app/uma/issue/ACX-451/all-txns-page-hide-stuck-pending-deposits
This PR filters out pending deposits older than 1 day
=> feat: filter out pending deposits older than 1 day

src/modules/airdrop/services/airdrop-service.ts
This PR automates a query that was used to be executed manually
=> fix: delete unprocessed wallet rewards (stage)

src/modules/deposit/dto.ts, src/modules/deposit/service.ts
=> feat: filter out pending deposits older than 1 day (prod)

src/modules/airdrop/services/airdrop-service.ts
This PR automates a query that was used to be executed manually
=> fix: delete unprocessed wallet rewards (prod)

src/modules/deposit/service.ts
=> feat: add V1 volume and deposits count to /deposits/stats (prod)

src/modules/scraper/entry-point/http/controller.ts, src/modules/scraper/entry-point/http/dto.ts
This PR adds an endpoint for submitting jobs to the consumer responsible for computing the `depositDate` based on the Deposit event block number
=> feat: add block number consumer

src/modules/airdrop/entry-points/http/controller.ts
=> fix: allow separate files upload (prod)

src/modules/referral/services/service.ts
The computation of `deposit_referral_stat` table takes a little bit long, so I'll add a few logs on the the staging env to figure out exactly what is happening
=> fix: add logs in computing referral stats

src/modules/referral/services/service.ts
This PR implements caching of the referral summary data
=> feat: cache referral summary data (stage)

src/modules/referral/services/service.ts
Production release of #156 
The referrals summary tests are failing because of the caching feature introduced in this PR. The tests will be resolved in an upcoming PR since this PR it's critical to be merged
=> feat: cache referral summary data (prod)

migrations/1669710834801-DepositsMv.ts, src/modules/deposit/model/DepositsMv.entity.ts, src/modules/deposit/model/deposit-referral-stat.entity.ts, src/modules/referral/model/DepositsFilteredReferrals.entity.ts, src/modules/referral/services/service.ts
Production deployment for #160
=> fix: fix materialized view query (prod)

src/modules/deposit/adapter/db/queries.ts
Decrease the time window for calculating the average fill time from 31 days to 24 hours
=> fix: calculate average fill time only for the last 24 hours

migrations/1669984610619-Deposit.ts, src/modules/deposit/adapter/db/queries.ts, src/modules/market-price/adapters/coingecko/index.ts, src/modules/market-price/services/service.ts, src/modules/scraper/adapter/messaging/DepositAcxPriceConsumer.ts, src/modules/scraper/adapter/messaging/TokenPriceConsumer.ts, src/modules/scraper/adapter/messaging/index.ts, src/modules/scraper/entry-point/http/controller.ts, src/modules/scraper/entry-point/http/dto.ts, src/modules/scraper/model/deposit.entity.ts, src/modules/scraper/module.ts, src/modules/scraper/service/ScraperQueuesService.ts
Production deployment which contains:
- #167 
- #168
=> feat: 🚀 release 2022-12-07

migrations/1669984610620-DepositsMv.ts, src/modules/configuration/index.ts, src/modules/deposit/model/DepositsMv.entity.ts, src/modules/referral/model/DepositsFilteredReferrals.entity.ts, src/modules/referral/services/queries.ts, src/modules/referral/services/service.ts
Production deployment which contains:
- #173
=> feat: 🚀 release 2022-12-12

src/modules/deposit/controller.ts, src/modules/deposit/dto.ts, src/modules/deposit/exceptions.ts, src/modules/deposit/service.ts, test/deposit.e2e-spec.ts
Closes ACX-506
Adds a new endpoint to be used on the FE on the "My Transactions" page. More info in the second approach section of t[his Linear task](https://linear.app/uma/issue/ACX-468/handle-new-unprofitable-condition-on-my-transactions-page).
=> feat: endpoint to get user deposits

src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts, src/modules/scraper/adapter/messaging/FillEventsConsumer.ts, src/modules/scraper/service/ScraperQueuesService.ts
I'm seeing a lot of jobs in the BlocksEvents queue. I'm increasing the concurrency of the consumer while investigating it
=> feat: increase blocks events consumer concurrency

src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts, src/modules/scraper/service/ScraperQueuesService.ts
Revert the temporary changes made in #189
=> fix: revert increase blocks events consumer concurrency

src/modules/referral/services/service.ts
=> fix: fix grouping deposits by claimed window (prod)

src/modules/configuration/index.ts
=> fix: fix cache default values (prod)

src/modules/scraper/entry-point/http/controller.ts, src/modules/scraper/entry-point/http/dto.ts, src/modules/scraper/service/ScraperQueuesService.ts
This PR adds an endpoint which retries failed messages from a particular queue
=> fix: add endpoint to retry failed jobs

src/modules/scraper/entry-point/http/controller.ts, src/modules/scraper/entry-point/http/dto.ts, src/modules/scraper/service/ScraperQueuesService.ts
=> fix: add endpoint to retry failed jobs (prod)

src/modules/scraper/adapter/messaging/BlockNumberConsumer.ts
Production deployment of #201. See description there
=> fix: don't retry consumer if deposit doesn't exist (prod)

src/modules/referral/services/service.spec.ts, src/modules/referral/services/service.ts
=> fix: fix referral address extraction (prod)

src/modules/ampli/index.ts, src/modules/scraper/adapter/amplitude/track-service.ts
=> refactor: rename fill event amplitude

src/modules/ampli/index.ts, src/modules/scraper/adapter/amplitude/track-service.ts
Production update of https://github.com/across-protocol/scraper-api/pull/205
=> refactor: rename fill event amplitude (prod)

src/modules/deposit/service.ts, test/deposit.e2e-spec.ts
=> fix: /deposits, exclude pending deposits with amount 0

src/modules/deposit/adapter/db/queries.ts, src/modules/deposit/entry-point/http/controller.ts, src/modules/deposit/entry-point/http/dto.ts, src/modules/deposit/entry-point/http/etl-controller.ts, src/modules/deposit/module.ts, src/modules/deposit/service.ts, test/deposit.e2e-spec.ts
This PR adds a `/etl/referral-deposits?date=` endpoint for serving referrals data for the ETL pipeline
=> feat: export referral data for ETL project

migrations/1681994187616-EventsSchema.ts, migrations/1681994187617-FundsDepositedEvent.ts, migrations/1681994187618-RequestedSpeedUpDepositEvent.ts, migrations/1681994187619-FilledRelayEvent.ts, src/modules/database/database.providers.ts, src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts, src/modules/scraper/adapter/messaging/FillEventsConsumer.ts, src/modules/scraper/module.ts, src/modules/web3/model/filled-relay-ev.entity.ts, src/modules/web3/model/funds-deposited-ev.entity.ts, src/modules/web3/model/index.ts, src/modules/web3/model/requested-speed-up-deposit-ev.entity.ts
This PR implements the storing of raw deposit, fill and speedup events as they will be needed when Across 2.5 contracts will be integrated
=> feat: store raw events

src/modules/market-price/adapters/coingecko/index.ts
=> feat: add support for SNX to cg service

migrations/1686902541959-Deposit.ts, src/main.ts, src/modules/deposit/adapter/db/deposit-fixture.ts, src/modules/deposit/model/deposit.entity.ts, src/modules/deposit/service.ts, src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts, src/modules/scraper/adapter/messaging/SpeedUpEventsConsumer.ts, src/modules/scraper/adapter/messaging/index.ts
* feat: support v2.5 speed ups
* add migration
=> feat: support v2.5 speed ups (#241)

src/modules/market-price/adapters/coingecko/index.ts
=> feat(price): add POOL market price support

src/modules/scraper/adapter/messaging/DepositReferralConsumer.ts, src/modules/scraper/adapter/messaging/TrackFillEventConsumer.ts
Temporary add some debugging logs for investigating an issue we have with one of the queues.
=> fix: add debugging logs

src/modules/deposit/service.ts
=> fix: reduce code in get user deposits handler

src/modules/deposit/entry-point/http/dto.ts, src/modules/deposit/service.ts, test/deposit.e2e-spec.ts
=> feat: add query params `startDepositDate` and `endDepositDate`

src/modules/deposit/entry-point/http/dto.ts, src/modules/deposit/service.ts, test/deposit.e2e-spec.ts
Clique requested this param in the v2/deposits endpoint
=> feat: add userAddress query param to /v2/deposits endpoint

src/modules/scraper/entry-point/http/controller.ts, src/modules/scraper/entry-point/http/dto.ts, src/modules/scraper/service.ts
Additional convenience admin endpoint for backfilling fee breakdowns
=> feat: admin endpoint for backfilling fee breakdowns

src/modules/referral/services/service.ts
=> fix: use correct deposit primary key

migrations/1700850247612-DepositsMv.ts, src/modules/referral/model/DepositsFilteredReferrals.entity.ts
This PR updates `deposits_filtered_referrals` VIEW to exclude deposits eligible for OP rewards
=> fix: update referral deposits view

src/modules/rewards/services/op-rebate-service.spec.ts, src/modules/rewards/services/op-rebate-service.ts
=> fix: make missing fee breakdown error message more descriptive

src/modules/scraper/adapter/gas-fees/gas-fees-service.ts, src/modules/scraper/adapter/messaging/FeeBreakdownConsumer.ts
Not 100% sure if this will fix ACX-1741 but should at least give a bit more insight in the logs I hope.
=> fix: refine fee breakdown errors and enforce filled status

src/modules/airdrop/entry-points/http/controller.ts, src/modules/airdrop/entry-points/http/dto.ts, src/modules/airdrop/services/airdrop-service.ts, src/modules/scraper/adapter/messaging/FeeBreakdownConsumer.ts, test/airdrop/merkle-distributor.e2e-spec.ts
Should be rebased on top of `master` after #333 is merged
=> feat: fetch proofs depending on rewards type

src/modules/configuration/index.ts, src/modules/web3/model/ChainId.ts, src/utils.ts
=> feat(linea): add support for linea

src/modules/deposit/utils.ts
=> fix: add deposit fill deadline to http response

src/modules/deposit/service.ts
Cache the total number of deposits for the `/tx-page` endpoint for 5 minutes to avoid successive `COUNT` SQL queries
=> fix: cache total deposits count for tx page

src/modules/configuration/index.ts, src/modules/scraper/service.ts
=> fix: keep distance from head when querying blocks events

src/modules/scraper/adapter/messaging/FeeBreakdownConsumer.ts
I noticed wrong `relayGasFeeAmount` values for deposits where the token decimals != 18. E.g.
=> fix: fee breakdown v3 events relay gas fee amount

src/modules/deposit/model/deposit.entity.ts, src/modules/scraper/adapter/messaging/FeeBreakdownConsumer.ts
We also want to track the swap fees for the fee breakdown
=> feat: add swap fees to fee breakdown

src/modules/scraper/adapter/messaging/FeeBreakdownConsumer.ts
The `relayGasFeePct` needs to be relative to the `bridgeFeePct`.
=> fix: relay gas fee pct

migrations/1718123954440-ArbReward.ts, src/modules/configuration/index.ts, src/modules/database/database.providers.ts, src/modules/market-price/adapters/coingecko/index.ts, src/modules/rewards/model/arb-reward.entity.ts, src/modules/rewards/module.ts, src/modules/rewards/services/arb-rebate-service.ts, src/modules/scraper/adapter/messaging/ArbRebateRewardConsumer.ts, src/modules/scraper/adapter/messaging/FeeBreakdownConsumer.ts, src/modules/scraper/adapter/messaging/index.ts, src/modules/scraper/entry-point/http/controller.ts, src/modules/scraper/module.ts, src/modules/scraper/service/ScraperQueuesService.ts
This PR implements the computation of ARB rebate rewards for deposits to Arbitrum
=> feat: implement computation of arb rewards

src/modules/rewards/services/arb-rebate-service.ts, src/modules/rewards/services/reward-service.ts
the ARB rewards are missing from the tx-page endpoint
=> fix: add arb rewards to tx history endpoint

src/modules/configuration/index.ts, src/modules/web3/model/ChainId.ts, src/utils.ts
We should sync stage and master also?
Closes ACX-2249
=> feat: add lisk and list sepolia

eslint.config.mjs, src/modules/rewards/services/arb-rebate-service.ts, src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts, src/modules/scraper/adapter/messaging/FillEventsV3Consumer.ts, src/modules/scraper/adapter/messaging/FindMissedFillEventConsumer.ts, src/modules/scraper/adapter/messaging/index.ts
We are now checking that the fill event hash matches de deposit event hash to discard invalid fills.
=> feat: including fill validation

eslint.config.mjs, src/modules/rewards/services/arb-rebate-service.ts, src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts, src/modules/scraper/adapter/messaging/FillEventsV3Consumer.ts, src/modules/scraper/adapter/messaging/FindMissedFillEventConsumer.ts, src/modules/scraper/adapter/messaging/index.ts
This reverts commit 9328bd32f91404b94b958425a1435313cb4ab875.
=> fix: revert fill validation

src/modules/configuration/index.ts, src/modules/web3/model/ChainId.ts, src/utils.ts
=> feat: add blast indexing

src/modules/configuration/index.ts
=> fix: blast provider

src/modules/scraper/adapter/messaging/TokenDetailsConsumer.ts
Fix USDB <-> DAI equivalency on Blast
=> fix: resolving output token on blast

src/modules/market-price/adapters/coingecko/index.ts
Allows us to track price of LSK
=> feat: add lsk cg price id

src/modules/configuration/index.ts, src/modules/web3/model/ChainId.ts, src/utils.ts
=> feat: add indexing of scroll

src/modules/scraper/adapter/messaging/TokenDetailsConsumer.ts
While checking the scraper logs, I saw there are deposit events with non valid ERC20 output tokens. We need to handle them explicitly and not fetch the token details as it doesn't exist.
=> fix: handle inexistent output token

src/modules/scraper/adapter/messaging/MerkleDistributorBlocksEventsConsumerV2.ts, src/modules/scraper/adapter/messaging/MerkleDistributorClaimConsumer.ts, src/modules/scraper/module.ts, src/modules/scraper/service.ts
This PR adds support for indexing and processing claim events from arb rewards contract
=> fix: process arb rewards claim events

src/modules/rewards/services/arb-rebate-service.ts, src/modules/rewards/services/reward-service.ts
This PR adds the ability to create jobs for computing the ARB reward airdrop data
=> fix: add jobs for arb airdrops

src/modules/configuration/index.ts, src/modules/web3/model/ChainId.ts, src/utils.ts
=> feat: add indexing for redstone

src/modules/configuration/index.ts, src/modules/web3/model/ChainId.ts, src/utils.ts
=> feat: add zora support

src/modules/configuration/index.ts, src/modules/rewards/services/op-rebate-service.ts, src/modules/web3/model/ChainId.ts, src/utils.ts
=> feat: add world chain support

src/modules/airdrop/services/airdrop-service.ts, src/modules/rewards/services/reward-service.ts
Related to: https://github.com/across-protocol/merkle-distributor/pull/15
=> fix: remove metadata object from rewards recipients

src/modules/configuration/index.ts, src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts, src/modules/scraper/service.ts, src/modules/web3/model/ChainId.ts, src/modules/web3/services/EthProvidersService.ts, src/utils.ts
Zion PR setting envs: https://github.com/UMAprotocol/zion/pull/599
=> feat: support Lens

src/modules/configuration/index.ts, src/modules/web3/services/EthProvidersService.ts
Zion PR removing envs and changing provider: https://github.com/UMAprotocol/zion/pull/654
=> chore: remove lens headers requirement
