src/modules/scraper/adapter/messaging/FillEventsConsumer.ts

https://linear.app/uma/issue/ACX-79/user-cannot-see-bridge-fees-and-rewards-on-ui

fix: fix capped realized lp fee

---

src/modules/referral/services/queries.ts
src/modules/referral/services/service.ts

This PR fixes the root cause of the numbers rounding bug. Now the amount of ACX rewards is always truncated

fix: decimals rounding

---

src/modules/scraper/service.ts

I need to undo this change because it was deployed to production due to a Zion issue. 
Actually I discovered that the code pushed to the `stage` branch was incorrectly deployed to production too

fix: temporary disable env var

---

src/modules/referral/services/queries.ts

https://linear.app/uma/issue/ACX-116/referrals-tx-incorrect-sorting
This is the deployment into production of the #45 staging PR
screenshot from production
screenshot from staging (it has the correct sorting)

feat: fix sorting bug

---

src/modules/scraper/service.ts

A very small number of FillRelay events (1-4 / day) are not fetched using the getLogs call. This change is meant only for testing

fix: try to reduce processed block upper limit

---

src/modules/referral/services/cron-service.ts

I increased the time between the cron that refreshes the `MATERIALIZED VIEW` and the cron that updates the sticky referral addresses. I suspect that the update of the sticky referral addresses takes more than 1 minute causing these to cron to overlap.
I also added some logs

fix: increase time difference between crons

---

src/modules/referral/services/cron-service.ts

I increased the time between the cron that refreshes the MATERIALIZED VIEW and the cron that updates the sticky referral addresses. This is only a temporary fix until tomorrow when I'll work on a nicer way to avoid these crons to overlap

fix: decrease crons frequency

---

src/modules/auth/auth.module.ts

`JwtStrategy` needs to be injected in order to enable processing JWT tokens from headers

fix: add JwtStrategy

---

docs/oauth.md
migrations/1663529363075-User.ts
migrations/1663940982693-User.ts
src/modules/auth/adapters/discord/api.ts
src/modules/auth/adapters/discord/index.ts
src/modules/auth/adapters/discord/model.ts
src/modules/auth/auth.module.ts
src/modules/auth/entry-points/http/auth.controller.ts
src/modules/auth/entry-points/http/discord.strategy.ts
src/modules/user/model/user.entity.ts
src/modules/user/services/user.service.ts

This PR updates the user entity and logic in order to store the Discord username and avatar. If the user is part of the Across Discord server, the global name and avatar are overwritten with the ones used on the server

feat: add discord server name and avatar

---

migrations/1664210580112-CommunityRewards.ts
migrations/1664210580112-WalletRewards.ts
package.json
src/app.module.ts
src/modules/airdrop/adapter/db/community-rewards-fixture.ts
src/modules/airdrop/adapter/db/wallet-rewards-fixture.ts
src/modules/airdrop/entry-points/http/controller.ts
src/modules/airdrop/entry-points/http/dto.ts
src/modules/airdrop/model/community-rewards.entity.ts
src/modules/airdrop/model/wallet-rewards.entity.ts
src/modules/airdrop/module.ts
src/modules/airdrop/services/airdrop-service.ts
src/modules/airdrop/services/exceptions.ts
src/modules/auth/entry-points/http/jwt.strategy.ts
src/modules/auth/entry-points/http/roles.ts
src/modules/database/database.providers.ts
src/modules/scraper/adapter/db/deposit-fixture.ts
src/modules/scraper/module.ts
src/modules/scraper/service.ts
src/modules/user/adapter/db/user-fixture.ts
src/modules/user/adapter/db/user-wallet-fixture.ts
src/modules/user/module.ts
src/modules/user/services/exceptions.ts
src/modules/user/services/user-wallet.service.ts
src/utils.ts
test/airdrop.e2e-spec.ts
test/user.e2e-spec.ts
yarn.lock

Changes:
- Add [models](https://github.com/across-protocol/scraper-api/tree/amatei/acx-290-add-endpoint-to-serve-wallet-rewards/src/modules/airdrop/model) for the Community Rewards and Wallet Rewards
- Add [endpoint](https://github.com/across-protocol/scraper-api/pull/84/files#diff-f91b21c92f2c60e94b5de8e3dcf5dc2b4bf31af44d40dc7c6d568ba1835f191eR13-R18) to get rewards for a particular wallet address
- Add [endpoint](https://github.com/across-protocol/scraper-api/pull/84/files#diff-f91b21c92f2c60e94b5de8e3dcf5dc2b4bf31af44d40dc7c6d568ba1835f191eR20-R42) to upload JSON files for populating the `community_rewards` and `wallet_rewards` tables
- Add a new [NestJS Guard](https://github.com/across-protocol/scraper-api/pull/84/files#diff-9acd83629deda2850757a03d3f6345dcc7e9583259d5b2ebfc795c99d941 …

feat: add wallet and community rewards

---

src/modules/airdrop/entry-points/http/controller.ts
src/modules/airdrop/services/airdrop-service.ts
src/modules/auth/entry-points/http/optional-jwt..ts
test/airdrop.e2e-spec.ts

`/airdrop/rewards?address=0x...`: Now, in order to fetch the community rewards component, the JWT token needs to be attached to the req

fix: fetch community rewards by JWT claims

---

src/modules/auth/adapters/discord/api.ts

https://linear.app/uma/issue/ACX-327/fix-discord-authentication
The discord auth endpoint throws an error if the user is not part of the Across Discord server. 
The correct flow is to ignore silently this error and use the global user details (name and avatar)

fix: handle Discord auth error

---

migrations/1666019035195-MerkleDistributorWindow.ts
migrations/1666019035196-MerkleDistributorRecipient.ts
src/modules/airdrop/adapter/db/merkle-distributor-recipient.ts
src/modules/airdrop/adapter/db/merkle-distributor-window-fixture.ts
src/modules/airdrop/entry-points/http/controller.ts
src/modules/airdrop/entry-points/http/dto.ts
src/modules/airdrop/model/merkle-distributor-recipient.entity.ts
src/modules/airdrop/model/merkle-distributor-window.entity.ts
src/modules/airdrop/module.ts
src/modules/airdrop/services/airdrop-service.ts
src/modules/airdrop/services/exceptions.ts
src/modules/database/database.providers.ts
test/airdrop/merkle-distributor-duplicate-window.json
test/airdrop/merkle-distributor.e2e-spec.ts
test/airdrop/merkle-distributor.json
test/jest-e2e.json

https://linear.app/uma/issue/ACX-352/scraper-api-endpoint-for-handling-created-tree
Changes in this PR:
- add [MerkleDistributorRecipient](https://github.com/across-protocol/scraper-api/blob/758d5a9d732533a25cc17e3f745e95e18bcb5d8d/src/modules/airdrop/model/merkle-distributor-recipient.entity.ts) and [MerkleDistributorWindow](https://github.com/across-protocol/scraper-api/blob/758d5a9d732533a25cc17e3f745e95e18bcb5d8d/src/modules/airdrop/model/merkle-distributor-window.entity.ts) entities
- [endpoint](https://github.com/across-protocol/scraper-api/blob/758d5a9d732533a25cc17e3f745e95e18bcb5d8d/src/modules/airdrop/entry-points/http/controller.ts#L65-L77) to upload JSON file for MerkleDistributor recipients (this endpoint is intended to be called by the [merkle-distributor publish-tree …

feat: inject and serve merkle distributor claims

---

src/modules/scraper/adapter/messaging/DepositReferralConsumer.ts

This PR improves the speed of the consumer that extracts the referral address and computes the sticky referral addresses. The query that computes the sticky referral addresses will now run only if the txn data doesn't contain a referral address

fix: improve referrals consumer (stage)

---

src/modules/airdrop/entry-points/http/controller.ts
src/modules/airdrop/entry-points/http/dto.ts
src/modules/airdrop/model/merkle-distributor-recipient.entity.ts
src/modules/airdrop/services/airdrop-service.ts
test/airdrop/merkle-distributor.e2e-spec.ts
test/airdrop/merkle-distributor.json

Add endpoint to retrieve all registered proofs for a given address. This is required for the referrals claiming. Also extends the payload of the recipients file to allow referral rewards as metadata.
Corresponding MerkleDistributor scripts PR https://github.com/across-protocol/merkle-distributor/pull/5

feat: GET /merkle-distributor-proofs

---

src/modules/airdrop/entry-points/http/controller.ts
src/modules/airdrop/services/airdrop-service.ts

This endpoint adds `/airdrop/welcome-traveller-eligible` and `/airdrop/community-rewards-eligible` endpoints for fetching eligible wallets for community rewards and welcome traveler rewards. These endpoints will be used by Chase to compute the final airdrop files

feat: add endpoint for eligible rewards wallets (stage)

---

src/modules/scraper/service.ts

The app crashed when a provider was configured, e.g. goerli, that didn't have a spokepool configured.

fix: typeerror when enable spokepool events processing (stage)

---

src/modules/referral/services/service.ts

While testing with some realistic data, I noticed a bug where ethers would throw an underflow error.

fix: parse bridgeFeeUsed with fixed precision

---

migrations/1668339782209-Deposit.ts
src/modules/deposit/adapter/db/queries.ts
src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts
src/modules/scraper/model/deposit.entity.ts

Changes
1. store the deposit event's relayer fee in the DB
2. improve the avg fill time query to include only the deposits from the past 30 days with relayer fee >= 0.0001

fix: improve avg fill time (stage)

---

src/modules/airdrop/services/airdrop-service.ts
test/airdrop.e2e-spec.ts

Changes `token.decimals` to `power(10, token.decimals)` in `depositCountQuery`

hotfix: fix decimals in welcome traveler completion script (prod)

---

src/modules/airdrop/services/airdrop-service.ts
src/modules/scraper/entry-point/http/controller.ts
test/airdrop.e2e-spec.ts

This PR reverts the query which returns the addresses eligible for BT rewards and also applies an upper bound date to eligible BT deposits

fix: revert bt eligible (prod)

---

src/modules/scraper/adapter/messaging/TokenDetailsConsumer.ts

If the deposit doesn't exist in the DB, disable the retry mechanism for the consumer that fetches the token details for that deposit

hotfix: don't retry token details for missing deposit

---

src/modules/airdrop/services/airdrop-service.ts
test/airdrop.e2e-spec.ts
test/airdrop/merkle-distributor.json

This PR adds a test to ensure that deposits after a certain date doesn't count for BT rewards `completed` flag

fix: add test for BT rewards

---

src/modules/airdrop/services/airdrop-service.ts

This PR caches for 5 minutes the response of the endpoint that returns the proofs for the merkle distributor contract

feat: add memory caching to proofs endpoint (prod)

---

migrations/1669710834801-DepositsMv.ts
src/modules/deposit/model/DepositsMv.entity.ts
src/modules/deposit/model/deposit-referral-stat.entity.ts
src/modules/referral/model/DepositsFilteredReferrals.entity.ts
src/modules/referral/services/service.ts

The current materialized view implementation contains a bug:
```sql
LEFT JOIN claim c on d."rewardsWindowIndex" = c."windowIndex" and (d."stickyReferralAddress" = c."account" or c.account = d."depositorAddr")
```
this join producing 2 rows for each deposit if the associated rewards were claimed by both referral and depositor

fix: fix materialized view query

---

src/logging.interceptor.ts

For each req the backend logs a message similar to `${method} ${endpoint} ${statusCode} ${statusMessage}`
This PR allows only 5xx and 4xx HTTP logs. Displaying logs on each requests make them unreadable during periods with high traffic

fix: clear HTTP logs

---

migrations/1669984610619-Deposit.ts
src/modules/market-price/adapters/coingecko/index.ts
src/modules/market-price/services/service.ts
src/modules/scraper/adapter/messaging/DepositAcxPriceConsumer.ts
src/modules/scraper/adapter/messaging/TokenPriceConsumer.ts
src/modules/scraper/adapter/messaging/index.ts
src/modules/scraper/entry-point/http/controller.ts
src/modules/scraper/entry-point/http/dto.ts
src/modules/scraper/model/deposit.entity.ts
src/modules/scraper/module.ts
src/modules/scraper/service/ScraperQueuesService.ts

- [add a new column to the `deposit` table that stores the ACX price at deposit time](https://github.com/across-protocol/scraper-api/pull/167/files#diff-c383b9143f9470ba7049fb7b2ebccf78fabf8ce0c860bc23468a19d5bfc11c42)
- [modify the MarketPrice service so that if the symbol is ACX and the requested date is before the token launch date, then return a hardcoded 0.1$ price](https://github.com/across-protocol/scraper-api/pull/167/files#diff-97817ef88b82b51f1edaad6e49f344c57d4b18b5fd086792981b5cc3bcd0732cR15-R32)
- [implement the `DepositAcxPriceConsumer` consumer which receives a deposit id and populates the `acxUsdPrice` column of the deposit table](https://github.com/across-protocol/scraper-api/pull/167/files#diff-de778566aa857d13a2988148a1c2e617fd3bfb0c99d2b453a8bc9a8e5e2604e6). The …

feat: 💲add ACX price to deposits

---

migrations/1669984610620-DepositsMv.ts
src/modules/configuration/index.ts
src/modules/deposit/model/DepositsMv.entity.ts
src/modules/referral/model/DepositsFilteredReferrals.entity.ts
src/modules/referral/services/queries.ts
src/modules/referral/services/service.ts

This PR updates the calculation of the referral rewards to use the `acxUsdPrice` column of the `deposit` table, instead of the hardcoded 0.1 value. [Here](https://github.com/across-protocol/scraper-api/pull/173/files#diff-435286f80a01293ba2937508138d0b82e9083a53499b7f2caafff986d2de05c8) you can see the updated queries

feat: 💲 integrate ACX price into referral rewards calculation

---

migrations/1670847543409-Deposit.ts
src/modules/configuration/index.ts
src/modules/scraper/adapter/across-serverless-api/suggested-fees-service.ts
src/modules/scraper/adapter/messaging/BlockNumberConsumer.ts
src/modules/scraper/adapter/messaging/SuggestedFeesConsumer.ts
src/modules/scraper/adapter/messaging/index.ts
src/modules/scraper/entry-point/http/controller.ts
src/modules/scraper/entry-point/http/dto.ts
src/modules/scraper/model/deposit.entity.ts
src/modules/scraper/module.ts
src/modules/scraper/service/ScraperQueuesService.ts
src/modules/suggested-fees/service.ts

Closes ACX-465
This PR adds a consumer that fetches the suggested fees from the Vercel API at the time a deposit gets indexed by the Scraper. If the deposit was made in the past, we check whether the deposit date is within a configurable threshold and fallback to 1bp if not.

feat: suggested fees consumer

---

migrations/1669984610621-DepositsMv.ts
src/modules/deposit/model/DepositsMv.entity.ts

Starting with 2022-12-13, we use the real ACX price for computing the referral rewards, so the referral bonus needs to be removed

feat: remove referral bonus

---

migrations/1670942459408-Deposit.ts
src/modules/configuration/index.ts
src/modules/deposit/service.ts
src/modules/scraper/model/deposit.entity.ts

Closes ACX-467
Add migration to use 1bp as the default value for `suggestedRelayerFeePct` because it can be updated by the consumer if appropriate. This also adapts the `where` clause to use the new column for pending deposits displayed in the "All Transactions" table.

feat: use `suggestedRelayerFeePct` in `GET /deposits` endpoint

---

migrations/1671299400000-Deposit.ts
src/modules/referral/services/service.ts
src/modules/scraper/model/deposit.entity.ts

This PR updates the logic for computing the referral rewards by grouping the deposits by the Claim events.

feat: reset referral rewards after claim

---

src/modules/scraper/service/ScraperQueuesService.ts

The ScraperQueuesService logs every minute the counts of each type or queue job: active, delayed, failed, etc. I'm seeing hundreds of failed jobs which shouldn't be there because BullJS is configured to delete failed jobs. I'm retrying them to see what happens

fix: retry failed jobs

---

src/modules/referral/services/service.ts

Consider only window > 0 when grouping deposits by claimed window for computing referral rewards

fix: fix grouping deposits by claimed window

---

src/modules/ampli/index.ts
src/modules/scraper/adapter/amplitude/track-service.ts
src/modules/scraper/adapter/messaging/TrackFillEventConsumer.ts

Closes ACX-569
@amateima my approach for later merging only the amplitude commits into `master` without the run mode changes is to use [cherry-pick](https://git-scm.com/docs/git-cherry-pick), roughly something like
```bash
git checkout master
git checkout -b amplitude-prod-update
git cherry-pick 12e211e331c010022960ca1a497f71bf8bddf86b # https://github.com/across-protocol/scraper-api/commit/12e211e331c010022960ca1a497f71bf8bddf86b
git cherry-pick 8760bd761566dd02425b3a20327a1815760c6886 # https://github.com/across-protocol/scraper-api/commit/8760bd761566dd02425b3a20327a1815760c6886
git cherry-pick <COMMIT_HASH_OF_THIS_PR_ON_STAGE>
git push -u origin amplitude-prod-update
```

refactor: rename ampli events and prop adjustments

---

src/modules/scraper/adapter/messaging/BlockNumberConsumer.ts

`BlockNumberConsumer` is a consumer attached to `BlockNumber` queue. It receives a deposit id and computes the deposit time based on the block number of the deposit. Currently, if the deposit doesn't exist in the DB (incorrect id), the job is retried infinitely. This can happen only if messages are published manually on this queue.

fix: don't retry consumer if deposit doesn't exist

---

src/modules/referral/services/service.spec.ts
src/modules/referral/services/service.ts

`subtractFunctionArgsFromCallData` function removes the function arguments from the calldata, returning only the arbitrary data that can be attached to a transaction. IF the calldata's length in bytes is less than the length of the deposit function signature `["address", "address", "uint256", "uint256", "uint64", "uint32"]` , then return empty string.

fix: fix referral address extraction

---

src/modules/deposit/dto.ts
src/modules/referral/entry-points/http/dto.ts

This PR updates validation of the query params in order to restrict `limit` and `offset` within a certain range

fix: improve query params sanitization

---

src/modules/airdrop/entry-points/http/controller.ts
src/modules/airdrop/entry-points/http/dto.ts
src/modules/airdrop/services/airdrop-service.ts
test/airdrop/merkle-distributor.e2e-spec.ts

This PR adds [the endpoint](https://github.com/across-protocol/scraper-api/pull/216/files#diff-f91b21c92f2c60e94b5de8e3dcf5dc2b4bf31af44d40dc7c6d568ba1835f191eR118-R123) used by across-etl scripts to fetch recipients of the MerkleDistributor airdrop contract

feat: serve merkle distributor recipients for etl tasks

---

src/modules/user/entry-points/http/user.controller.ts
src/modules/user/services/user-wallet.service.ts
test/user.e2e-spec.ts

This PR adds a new endpoint `/users/etl/discord-wallets` used to retrieved the wallets linked by discord users. This endpoint canbe called only with a JWT admin token

feat: add endpoint for discord users linked wallet

---

src/modules/deposit/service.ts

The property will be needed on the FE for speeding up v2.5 events. This change should also not break the current FE.

feat: return `recipientAddr` for /deposits endpoint

---

src/modules/configuration/index.ts
src/modules/scraper/blocks.spec.ts
src/modules/scraper/utils.ts
src/modules/web3/services/abi/ArbitrumSpokePool2_5.json
src/modules/web3/services/abi/EthereumSpokePool2_5.json
src/modules/web3/services/abi/OptimismSpokePool2_5.json
src/modules/web3/services/abi/PolygonSpokePool2_5.json

This PR adds the new SpokePool contracts and also fixes a bug in the logic that decides which contracts need to be queried depending on the block range

fix: add SpokePool2.5 contracts

---

src/modules/deposit/entry-point/http/controller.ts
src/modules/deposit/entry-point/http/dto.ts
src/modules/deposit/exceptions.ts
src/modules/deposit/service.ts
test/deposit.e2e-spec.ts

This endpoint allows to retrieve a single deposit based on the `depositTxHash` and `originChainId`.
We need this endpoint for the DODO aggregator integration. See https://github.com/DODOEX/dodo-bridge-aggregator#ii-status

feat: GET /deposits/details endpoint

---

src/modules/scraper/entry-point/http/controller.ts
src/modules/scraper/entry-point/http/dto.ts
src/modules/scraper/service/ScraperQueuesService.ts

Add an optional `count` parameter to specify how many queue jobs needs to be retried when calling the `scraper/failed-jobs/retry` endpoint.
**Issue**
With the current implementation, if the queue has many failed messages that need to be retried, the NodeJS app runs out of memory

fix: add count when retry jobs

---

migrations/1686902541959-Deposit.ts
src/main.ts
src/modules/deposit/adapter/db/deposit-fixture.ts
src/modules/deposit/model/deposit.entity.ts
src/modules/deposit/service.ts
src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts
src/modules/scraper/adapter/messaging/SpeedUpEventsConsumer.ts
src/modules/scraper/adapter/messaging/index.ts

Fixes ACX-1219
For some reason, we didn't adapt the scraper to support the new speed up events of v2.5 of the spoke pools.

feat: support v2.5 speed ups

---

src/modules/configuration/index.ts
src/modules/scraper/entry-point/http/controller.ts
src/modules/scraper/entry-point/http/dto.ts
src/modules/scraper/service.ts

Some deposits from the database don't have a deposit date, token id or a price id and this should not happen under any circumstances.
Until I figure out exactly why it happens, I added a new endpoint `/scraper/incomplete-deposits/retry` that queries these deposits and submits them to the `BlockNumber` queue again. This will force the columns to be populated

fix: retry incomplete deposits

---

cloudbuild-stage.yml
cloudbuild.yml

Change the docker registry method from GCR to Artifacts due the [near deprecation from GCP](https://cloud.google.com/container-registry/docs/deprecations/container-registry-deprecation)

feat: Update docker registry

---

src/modules/referral/services/queries.ts
src/modules/scraper/adapter/messaging/DepositReferralConsumer.ts

Fix the query that updates the sticky referral address of the deposits made by a particular depositor address.

fix: fix sticky referral address query

---

migrations/1696942295195-ReferralRewardsWindowJob.ts
migrations/1696942295196-ReferralRewardsWindowJobResult.ts
src/modules/database/database.providers.ts
src/modules/referral/adapter/db/referral-rewards-window-job-fi.ts
src/modules/referral/entry-points/http/controller.ts
src/modules/referral/entry-points/http/dto.ts
src/modules/referral/model/ReferralRewardsWindowJob.entity.ts
src/modules/referral/model/ReferralRewardsWindowJobResult.entity.ts
src/modules/referral/module.ts
src/modules/referral/services/exceptions.ts
src/modules/referral/services/service.ts
test/referrals.e2e-spec.ts

The computation of referral rewards is triggered by calling the POST referrals/merkle-distribution endpoint, but the process is synchronous and the HTTP request waits for the data to be returned. The problem with this approach is that the computation of referral rewards can take a long time and if it takes longer than 100 seconds, the endpoint won't return any data because Cloudflare will throw a timeout error.
With this new approach, the endpoint `POST referral-rewards-window-job` is used to create an asynchronous job which can be queried later for results by calling the  `GET referral-rewards-window-job/:id` endpoint.

fix: implement asynchronous jobs for computing referral rewards window

---

src/modules/deposit/adapter/db/deposit-fixture.ts
src/modules/deposit/entry-point/http/controller.ts
src/modules/deposit/entry-point/http/dto.ts
src/modules/deposit/service.ts
test/deposit.e2e-spec.ts

Move the logic that returns the pending deposits in a separate endpoint `/deposits/pending` because this logic is quite particular (filter out deposits older than 1 day and unprofitable deposits) and it needs to be taken out from the `/deposits` endpoint which is an endpoint suitable for more general use case.
The endpoint change must be made in the FE too

fix: separate endpoint for pending deposits

---

src/modules/deposit/entry-point/http/controller.ts
src/modules/deposit/entry-point/http/dto.ts
src/modules/deposit/service.ts
test/deposit.e2e-spec.ts

I added a new `GET /deposits-v2` endpoint which is used to serve deposits. This endpoint is intended to replace `/deposits` in time because the old endpoint contains specific logic for some particular filters: for example if deposits are filtered by the `pending` status, it returns only profitable deposits happening in the past 24hrs. This kind of specific logic needs to go to dedicated endpoints, while the new `/deposits-v2` endpoint allows only simple filtering and sorting operations

fix: add new endpoint to serve deposits

---

src/modules/deposit/service.ts

Closes ACX-1670
On the FE, we make use of the `fillTime` in the new deposits table.

feat: expose `fillTime` in deposits endpoint

---

src/modules/referral/entry-points/http/controller.ts
src/modules/referral/entry-points/http/dto.ts
src/modules/referral/services/cron-service.ts
src/modules/referral/services/service.ts
test/referrals.e2e-spec.ts

This PR adds the `fields` query parameter to the `/referrals/summary` endpoint which allows to fetch only a subset of the fields returned by the endpoint.  
`GET /referrals/summary?address=${referrer}&fields[]=referralRate&fields[]=tier` endpoint returns only the referral rate and the referral tier

fix: add endpoint for referral rate

---

src/modules/referral/services/service.ts
src/modules/scraper/adapter/messaging/BlockNumberConsumer.ts
src/modules/scraper/adapter/messaging/DepositReferralConsumer.ts
src/modules/scraper/adapter/messaging/RectifyStickyReferralConsumer.ts
src/modules/scraper/adapter/messaging/index.ts
src/modules/scraper/entry-point/http/controller.ts
src/modules/scraper/entry-point/http/dto.ts
src/modules/scraper/module.ts
src/modules/scraper/service.ts
src/modules/scraper/service/ScraperQueuesService.ts
test/sticky-referral-address.e2e-spec.ts

This is a refactoring of the mechanism used for extracting the referral address and computing the sticky referral address
**How it works**
1. A message containing a `depositId` is submitted on the `DepositReferral` queue and it is processed by [DepositReferralConsumer](https://github.com/across-protocol/scraper-api/blob/9d7e48c26723c680e58a0719c698d337fce03fcf/src/modules/scraper/adapter/messaging/DepositReferralConsumer.ts#L25-L55). This consumer has only 1 job: it extracts the referral address from the tx data or it derives the sticky referral address from previous deposits made by the same depositor
2. The consumer from above also publishes a message on the `RectifyStickyReferral` queue and the message is processed by [RectifyStickyReferralConsumer](https://github.com/across-protocol/sc …

fix: refactor referral address mechanism

---

src/modules/deposit/entry-point/http/controller.ts
src/modules/deposit/entry-point/http/dto.ts
src/modules/deposit/service.ts
test/deposit.e2e-spec.ts

During QA of the new transactions page here https://github.com/across-protocol/frontend-v2/pull/910, new requirements were:
- add more filters in the future
- and have a single deposits table that shows pending deposits first and then sorts by date
This PR adds these functionality to the new `/deposits/tx-page` endpoint.

feat: new `/deposits/tx-page` endpoint for FE

---

src/modules/deposit/entry-point/http/dto.ts
src/modules/deposit/service.ts
test/deposit.e2e-spec.ts

Based on https://github.com/across-protocol/scraper-api/pull/296#pullrequestreview-1746039964 but opening a new PR because branch name changed.

feat: add `include` query params to deposits v2 query

---

src/app.module.ts
src/modules/deposit/entry-point/http/dto.ts
src/modules/deposit/model/DepositsMv.entity.ts
src/modules/deposit/module.ts
src/modules/deposit/service.ts
src/modules/deposit/utils.ts
src/modules/referral/services/queries.ts
src/modules/referral/services/service.ts
src/modules/rewards/adapter/db/reward-fixture.ts
src/modules/rewards/module.ts
src/modules/rewards/services/op-rebate-service.ts
src/modules/rewards/services/reward-service.ts
src/modules/scraper/module.ts
test/deposit.e2e-spec.ts

Closes ACX-1714
This adds a new `RewardService` in `src/modules/rewards/services/reward-service.ts` which serves as an umbrella service for all reward-related functionality. This service is used by the deposits module to include related rewards for a deposit.
Requires #286

feat: include rewards to /deposits/tx-page response

---

src/modules/scraper/adapter/messaging/FeeBreakdownConsumer.ts
src/modules/scraper/utils/fees.spec.ts
src/modules/scraper/utils/fees.ts
src/modules/web3/model/tx-receipt.entity.ts

The `FeeBreakdownConsumer` didn't correctly handle `0` values. If a slow fill, for example, occurs then the `relayerFeePct` is `0`.

fix: fee breakdown zero values

---

src/modules/referral/services/service.ts

`GET /rewards/referrals` was crashing due usage of wrong id

fix: use correct deposit primary key

---

src/modules/rewards/services/op-rebate-service.ts
test/deposit.e2e-spec.ts

For some reason TypeORM errors with
```
QueryFailedError: syntax error at or near ")"
at .PostgresQueryRunner.query ( /usr/src/app/src/driver/postgres/PostgresQueryRunner.ts:299 )
at .runMicrotasks
at .processTicksAndRejections ( node:internal/process/task_queues:96 )
at .SelectQueryBuilder.loadRawResults ( /usr/src/app/src/query-builder/SelectQueryBuilder.ts:3555 )
at .SelectQueryBuilder.executeEntitiesAndRawResults ( /usr/src/app/src/query-builder/SelectQueryBuilder.ts:3320 )
at .SelectQueryBuilder.getRawAndEntities ( /usr/src/app/src/query-builder/SelectQueryBuilder.ts:1597 )
at .SelectQueryBuilder.getMany ( /usr/src/app/src/query-builder/SelectQueryBuilder.ts:1687 )
at .OpRebateService.getOpRebateRewardsForDepositPrimaryKeys ( …
```

fix: op rebate rewards for empty deposit pks

---

src/modules/scraper/adapter/messaging/DepositFilledDateConsumer.ts
src/modules/scraper/adapter/messaging/FillEventsConsumer.ts
src/modules/scraper/adapter/messaging/FillEventsConsumer2.ts

I noticed a lot of errors in the logs
```
Dec 13 16:01:22 api-scraper-across-prod docker[4194253]: [Nest] 87  - 12/13/2023, 4:01:22 PM   ERROR [TrackFillEventConsumer] TrackFillEvent {"depositId":3424031,"destinationToken":"0x5AEa5775959fBC2557Cc8789bC1bf90A239D9a91","fillTxHash":"0x7b762c4555aaab29cc3d0551c488b8d2f9f2551c536d8ad06e9284861503c8c7"} failed: Error: Fill tx does not have a date
```
This PR aims to decrease the logs by publishing the track fill message in the `DepositFilledDateConsumer` to make sure that the filled date is populated

fix: publish track fill event job in filled date consumer

---

src/modules/scraper/entry-point/http/controller.ts
src/modules/scraper/entry-point/http/dto.ts
src/modules/scraper/service.ts

Admin endpoint for setting `filledDate`.
There are quite a lot of deposits where filled date is null even though they are filled. This is also causing a lot of errors in `TrackFillEventsConsumer`

feat: add endpoint for backfilling filledDate

---

src/modules/deposit/service.ts

the `/tx-page` endpoint has poor performance as `offset` param increase. Temporarily limit offset to 1500 until we fix it. Most probably we need to add an index on the deposit table

fix: temp limit offset on tx-page endpoint

---

src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts

Set the depositor as being the transaction sender for deposits made through the SpokePoolVerifier contract

fix: set depositor address correctly for deposits made through SpokePoolVerifier contract

---

src/modules/scraper/adapter/messaging/CappedBridgeFeeConsumer.ts
src/modules/scraper/adapter/messaging/CappedBridgeFeeUsdConsumer.ts
src/modules/scraper/adapter/messaging/FillEventsV3Consumer.ts
src/modules/scraper/adapter/messaging/index.ts
src/modules/scraper/module.ts
src/modules/scraper/service/ScraperQueuesService.ts

This PRs [removes the computation of the capped bridge fee pct](https://github.com/across-protocol/scraper-api/pull/353/files#diff-ecfac74c90bff76d0ddbb76c32110ca565d1b91dfebb79fce0ea9f9ad8a3d175L54) from the consumer that process V3 fill events and moves it to its own dedicated & retryable consumer: [CappedBridgeFeeConsumer](https://github.com/across-protocol/scraper-api/pull/353/files#diff-5f582b450e40be10f254993aa396a690607a8296a2f0a84b256bf968f2da7694). 
The reason is simple: for V3 deposits, the computation of the bridge fee percentage needs the prices of the input & output token. Fetching prices is done asynchronously, in a different consumer,  so there's no guarantee that they are available by the time the fills are processed for a particular deposit.
⚠️  Also, the bridge fee pct …

fix: improve capped bridge fee pct

---

src/modules/scraper/adapter/messaging/BlocksEventsConsumer.ts

The initial message field was set incorrectly for v3 FundsDeposited events.

fix: set correct initial message field for v3

---

migrations/1711039047259-DepositGapCheck.ts
src/modules/configuration/index.ts
src/modules/database/database.providers.ts
src/modules/deposit/service.ts
src/modules/monitoring/module.ts
src/modules/scraper/adapter/db/DepositGapCheckFixture.ts
src/modules/scraper/model/DepositGapCheck.entity.ts
src/modules/scraper/module.ts
src/modules/scraper/service/DepositGapService.ts
src/modules/scraper/service/DepositsGapDetectionCron.ts
test/scraper/deposit-gap.e2e-spec.ts

This PR adds deposit gap detection in the Across scraper.
**How it works:**
1. There's a new [deposit_gap_check](https://github.com/across-protocol/scraper-api/pull/368/files#diff-8359bea7a41a52f7fd73f2d59269c452b53ea0b924d477138c705a895afbdad4) table which stores the last deposit id that passes the gap check, meaning that they don't have gaps preceding them. This is useful to detect missing deposit events that need to be re-scraped.
2. There's a new [DepositGapService](https://github.com/across-protocol/scraper-api/pull/368/files#diff-1ed0239b8ef38c1d46359b1f174359ec4e31f67a1e4544ca9497427b02e7b1e1) which contains useful the logic for managing deposits gaps. 
The most important function is `checkDepositGaps()` that returns and object containing the following properties: 
- gapIntervals - …

feat: add deposit gap check

---

src/modules/scraper/adapter/messaging/DepositFilledDateConsumer.ts

For each fill transaction stored in the DB, get the date from the receipt instead of the tx

fix: get filled date from receipt

---

src/modules/rewards/services/op-rebate-service.ts

This PR fixes a bug that was causing negative OP rewards when the bridge fee is negative. This fix will not allow computed OP rewards to go below 0

fix: fix op reward bug

---

src/modules/web3/services/EthProvidersService.ts

The usage of `JsonRpcProvider` triggers additional `eth_chainId ` calls with every RPC call we make in order to ensure that the provider url matches the network. This is not necessary because the scraper doesn't change the providers, so we are safe to use `StaticJsonRpcProvider`

fix: replace json rpc with static json rpc provider

---

src/modules/scraper/service.ts

This PR increase the buffer we keep from the head block when querying events for chains with lower block time

fix: increase distance from head block

---

src/modules/airdrop/entry-points/http/dto.ts
src/modules/airdrop/services/airdrop-service.ts
src/modules/rewards/model/RewardsWindowJob.entity.ts
test/airdrop/merkle-distributor.e2e-spec.ts

This PR adds the ability to serve arb rewards proofs and also removes some old functionality from the rewards

fix: serve arb rewards proofs

---

src/modules/scraper/adapter/messaging/FeeBreakdownConsumer.ts

If `bridgeFeeUsd` is 0 than `relayGasFeePct` should be 0, otherwise `.dividedBy(bridgeFeeUsd)` will fail (division by 0)

fix: fix fee breakdown

---

src/modules/scraper/adapter/messaging/FeeBreakdownConsumer.ts

Check if the token is supported by the pricing API before querying the price

fix: fix bridge fee breakdown consumer

---

.github/workflows/lint-build-test.yaml
src/modules/configuration/index.ts

The first deposit id on Redstone is 1 actually. This shouldn't have had an impact on the production Scraper because indexing of Redstone is not enabled yet.

fix: redstone first deposit id

---

src/modules/scraper/adapter/messaging/FindMissedFillEventConsumer.ts
src/modules/scraper/service/CheckMissedFillEventsCron.ts

The cron we use to look for missed fill events checks up to 1000 deposits each time. Since there are more than 1000 pending deposits in the database, for the thousand we were processing each run, we were founding only a dozen of fills. 
To avoid that, this PR modifies the query we do to order deposits by deposit date to check first the most recent ones.
It also fix a bug that kept suspended 'FindMissedFillEvent" jobs looping. Now they will stop running once the status is changed to suspended.
I'm still looking why we are missing so much fill events when we process blocks, specially on Base. But in the meantime, this should help us find more missed fills.

fix: missed fill event cron

---

src/modules/scraper/adapter/messaging/FindMissedFillEventConsumer.ts

Some missed fill event jobs are ending up as 'suspended' because our search for fills is starting from a block that's older than the block where the fill actually occurred.
For example, our lookup for [this fill](https://arbiscan.io/tx/0x113b5502c30d1717560d45779b4d083abe4549dd85e6d340de38c6cb0b1d6350) began at block 245189953, but the fill happened one block before, in 245189952.
This issue is happening frequently on Arbitrum and zkSync.

fix: block range search for find missed fill event process

---

migrations/1736706626171-OpRewardsStats.ts
src/modules/database/database.providers.ts
src/modules/rewards/model/op-rewards-stats.entity.ts
src/modules/rewards/module.ts
src/modules/rewards/services/OpRewardsStatsCron.ts

This PR stores in DB how much OP have been earned so far. 
The next step is to check in the `OpRebateRewardConsumer` that the total OP earned is less than 750K. If so, OP rewards will not be allocated to deposits.
`SUM` is a relatively expensive query so it would have been ineficient to compute the sum for each deposit eligible for OP rewards. My approach was to use a precomputed value

fix: track earned op rewards

---

src/modules/rewards/entrypoints/http/controller.ts
src/modules/rewards/services/op-rebate-service.ts
src/modules/rewards/services/reward-service.ts
src/modules/scraper/module.ts

`GET /rewards/op-rebates/stats`
```
{
"totalTokenAmount": "<WEI_OP_AMOUNT>",
}
```

feat: add endpoint to serve op rebates stats
